program arcn_compliance_v1.aleo;

function report:
    input r0 as address.public;
    input r1 as address.public;
    input r2 as field.public;
    input r3 as field.public;
    input r4 as u128.public;
    input r5 as u128.public;
    assert.eq true true;

function report_voucher:
    input r0 as address.public;
    input r1 as address.public;
    input r2 as field.public;
    input r3 as u128.public;
    assert.eq true true;
