const {Cell} = require('@ton/core');
const c = Cell.fromBase64('te6cckEBAgEAGQACJUQcOe0AAAAAAAAAAICcRJxEnEUBAQAALnKiTA==');
const s = c.beginParse();
console.log('bits:', s.remainingBits, 'refs:', s.remainingRefs);
console.log('op:', '0x'+s.loadUint(32).toString(16));
console.log('qid:', s.loadUint(64));
console.log('is_from_admin:', s.loadBit());
console.log('has_admin:', s.loadBit());
console.log('has_controller:', s.loadBit());
console.log('has_tickSpacing:', s.loadBit());
console.log('has_sqrtPriceX96:', s.loadBit());
console.log('has_activate_pool:', s.loadBit());
console.log('remaining bits after flags:', s.remainingBits);
const pf=s.loadUint(16);
console.log('protocolFee:', pf, pf===10001 ? '(IMPOSSIBLE_FEE)' : '');
const lf=s.loadUint(16);
console.log('lpFee:', lf, lf===10001 ? '(IMPOSSIBLE_FEE)' : '');
const cf=s.loadUint(16);
console.log('currentFee:', cf, cf===10001 ? '(IMPOSSIBLE_FEE)' : '');
console.log('refs left:', s.remainingRefs);
const r1=s.loadRef();
console.log('ref1 bits:', r1.bits.length);
const r2=s.loadRef();
console.log('ref2 bits:', r2.bits.length);
console.log('after both refs - bits:', s.remainingBits, 'refs:', s.remainingRefs);
